### ISSUE TITLE
Empty Check

### ISSUE THREAD

**Issue by mDehning** [Kordishal/generator-issues#1]
Something to react to the fact the result of a genvar is undefined / empty / blank after trim(). 

**UseCase:**
Tag based generators, sometimes there are empty results on purpose, sometimes a variable is not filled in a specific path

**Comment by iamromeo** [comment]
[emptycheck:genvar-name] .... [/emptycheck]
if true - print the in between 
if false - delete the in between

**Comment by mDehning** [comment]
Quick Clarification: 

[emptycheck:genvar-name] .... [/emptycheck]
if true - print the in between
if false - delete the in between and **print the genvar value**
