### ISSUE TITLE
Variable Names for Router Output and Subsequent Hierarchical Naming

### ISSUE THREAD

**Issue by mDehning** [Kordishal/generator-issues#12]
Sometimes I want to reuse - or differentiate - the output of a router.

I would like to give it a name so the result can be queried in [genvar] as well

If the output of a router is a simple template, I would like to add this name as prefix to all variables generated within this template, to prevent overrides.

Use Case:
- Output of transformer, when deriving a property from a roll (for example deriving the element from a magical thing)
- creating multiple persons of specific types and wanting to refer to individual parts of the person without having to again call a generator. 
  - For example resuing the Last Name in a following paragraph describing a conflict between two characters.

**Comment by Kordishal** [comment]
Variable names are implemented. Hierarchical naming will probably need a new issue later.
