### ISSUE TITLE
Please allow alternate input for text of the ‘roll dice’ button

### ISSUE THREAD

**Issue by shyredfox** [Kordishal/generator-issues#22]
**Is your feature request related to a problem? Please describe.**
I would like to be able to enter alternate text for the ‘roll the dice’ button. For cities and towns this makes sense. But if you want to generate responses - it would look better to have say ‘press for response’. 

**Describe the solution you'd like**
I’d like to see an optional text input box that allows us to name the ‘roll the dice’ button.

**Describe alternatives you've considered**
I would do CSS, but I can’t do that for the generators page. And I can’t substitute text for a button with CSS. I could do an image, if I could modify CSS for a generator.

**Additional context**
the current generator is great for RPG items one might need on the fly. But for world interaction, not so good. I think allowing us to name the ‘roll the dice’ button would allow for fun world interactions.

**Comment by Kordishal** [comment]
This is done
