### ISSUE TITLE
Public page should include link to author profile

### ISSUE THREAD

**Issue by Kordishal** [Kordishal/generator-issues#24]
**World Anvil Username**: SoulLink
**What is the problem?**
It is non-obvious who made a random generator. 

**Describe the solution you'd like**
It would be nice to just have a link to the author profile on the public page of a Random Generator. Removes the necessity to add that link yourself each time into the sidebar.

**Describe alternatives you've considered**

**Comment by iamromeo** [comment]
That is already done
