### ISSUE TITLE
Article template public page has white background in deep blue interface theme

### ISSUE THREAD

**Issue by Kordishal** [Kordishal/generator-issues#26]
**World Anvil Username**: SoulLink
**What is the problem?**
While viewing an article template the background is light in the deep blue interface theme.
**Describe the solution you'd like**
Dark background matching the rest of the theme.

**Describe alternatives you've considered**

![image](https://user-images.githubusercontent.com/14262536/120796295-f2f74b00-c53a-11eb-9b65-c3de8c671edc.png)

**Comment by iamromeo** [comment]
fixed
