### ISSUE TITLE
Random Generator Article Embeds

### ISSUE THREAD

**Issue by graylion-wa** [Kordishal/generator-issues#28]
A few things

In many case I would embed a generator specific to the article.

City Watch Article
Embedded City Watch Generator
(In a secret)

Pantheon Article
Embedded Church, Priest or God.

Trapped Encounter
Embed Trap Generator to its unique each time

Targeting the BBCode / Results of the generator with CSS easier in an article. 

The article is the first approach for reaching most things in the world and I (my opinion) find it easier to reach on the presentation side, vs going to the edit side to reach the presentation side of the generator. 

And you already mentioned the DSTS

This is my previous iteration in an article which was super handy 

https://www.worldanvil.com/w/creation/a/city-encounter-article

Thank you for considering this

**Comment by graylion-wa** [comment]
![20210608_075308.jpg](https://user-images.githubusercontent.com/79761754/121180269-abb8d500-c82e-11eb-9fae-189db5023e48.jpg)

![20210608_075333.jpg](https://user-images.githubusercontent.com/79761754/121180278-aeb3c580-c82e-11eb-993a-d9741d6d2504.jpg)

**Comment by shyredfox** [comment]
I would love to see this. I *think* it’s what I’d thought the generators would be from the beginning. It could add so much interactivity to articles. As an author, I think it would be fun to have a generator for example what a character could say in answer to a question. It could also add a dimension for stories - like a randomized twist on choose your own adventure.

**Comment by graylion-wa** [comment]
![20210608_075742.jpg](https://user-images.githubusercontent.com/79761754/121180824-46b1af00-c82f-11eb-91d7-77d90b3e9fb3.jpg)

**Comment by denversg1** [comment]
I would use simple string generators (as tagged lists) on my articles, to display lists of loot by rarity/setting, encounters by the biome they are tagged with,  could also be used to generate a random npc or name that isn't currently assigned to a story element to then assign them to a quest or something, a generator for traps or dangers for a particular area/setting. Plenty of d&d related use cases for worldbuilding and running a game. <3
