### ISSUE TITLE
Remove the inline CSS styling with the !important for the text on the 'Roll the Dice' button in articles

### ISSUE THREAD

**Issue by shyredfox** [Kordishal/generator-issues#36]
**World Anvil Username**: Shyredfox
**What is the problem?**
I would like to be able to increase the text size on the 'Roll the Dice' button. The only way I could figure out how to do this was via a per generator id that looked like this: #template_render_{some alphanumeric string} strong{ font-size: 2rem !important; } that I would have to put on each article. Not ideal. 

**Describe the solution you'd like**
I'd love to see that styling moved into a .css, so we can tweak it easily. (Pretty please)

**Describe alternatives you've considered**
Please see the "What is the problem?" for what I was able to figure out. Trying to put a container around the generator with a bigger text class did not work either.

Thanks for considering! <3

Suggestion was originally from Tim - The Sea of Starlight. But I had wanted the same thing. Didn't see it written up for a while, so I did.

**Comment by iamromeo** [comment]
Fixed @Kordishal
